### ISSUE TITLE
[Feature Request]: CC:Tweaked compatibility

### ISSUE THREAD

**Issue by Karotte128** [terrarium-earth/Botarium#34]
### Is your feature request related to a problem?

It would be great if it is possible to read (energy-)values of blocks created with this mod.

### Solution(s)

Make things appear as computercraft peripherals.

### Mod Version

the newest version

### Mod Loader Version

1.20.1-?

### Mod Loader

Fabric

### Additional context

I dont know if this needs to be done on this mod (I know this is a libary mod) or on mods that use this mod.

**Comment by CodexAdrian** [comment]
Im a little confused, does CC tweaked have something in it that allows it to read energy levels on a block? Botarium's purpose is to create a multiplatform energy container that can then be registered to the respective mod loaders for mod compatibility. It should automatically be compatible with CC: Tweaked if they read the energy capability on a block.

**Comment by Karotte128** [comment]
I have to test it. It should have some comptatibility with energy containers, but I think it needs to be activated somehow.

**Comment by CodexAdrian** [comment]
I see. I took a look at their repository, CC: Tweaked is a multiplatform mod. If they have a system for registering it, it should already be available to mods trying to be multiplatform and mod authors who want this can import CC: Tweaked directly without issue. If theres anything Botarium is doing that specifically makes it incompatible with CC: Tweaked let me know, but otherwise I don't really see what Botarium needs to do here to make it more compatible

**Comment by Karotte128** [comment]
Ok. Thank you.
